spring.application.name=3d-task

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

aws.accessKeyId=${AWS_ACCESSKEYID}
aws.secretKey=${AWS_SECRETKEY}
aws.region=${AWS_REGION}
aws.endpoint=${AWS_ENDPOINT}
aws.bucket=${AWS_BUCKET}

jwt.secretKey=${JWT_SECRET}