spring.application.name=3d-task

spring.datasource.url=jdbc:postgresql://localhost:1337/postgres
spring.datasource.username=postgres
spring.datasource.password=paralich

aws.accessKeyId=minioadmin
aws.secretKey=minioadmin
aws.region=us-east-1
aws.endpoint=http://localhost:9000
aws.bucket=3d-task